"""Unified RL data, parser and reward contracts for the two-stage task.

Stage 4A scope: the reusable interfaces future RL training consumes —
RL samples (resolved-only, target.category_id as the only label), the VeRL
v0.9.0 native-tool five-field RL parquet exporter/validator, the unified output parser
(agent.task.parser.check_*), and the shared task reward. No training
algorithm, rollout engine, vLLM/Ray or GPU code lives here.
"""

from .dataset import (
    RL_SPLITS,
    VERL_RL_COLUMNS,
    export_rl_dataset,
    validate_rl_row,
    validate_rl_dataset,
)
from .reward import (
    FULL_REWARD,
    INVALID_REWARD,
    STAGE1_VALID_MISS_DEFAULT,
    STAGE2_PARTIAL_DEFAULT,
    RewardConfig,
    RewardResult,
    reward_for_choice_result,
    reward_for_parse_result,
    reward_stage1,
    reward_stage1_choices,
    reward_stage2,
    reward_stage2_choices,
)
from .sample import (
    NATIVE_TOOL_TRAJECTORY_FORMAT,
    RewardMeta,
    RlMessage,
    RlSample,
    build_native_tool_prompt,
    build_rl_row,
    build_rl_samples,
    visible_metadata,
)
from .native_tools import (
    CategoryToolEnvironment,
    FinalToolAnswer,
    exact_tool_reward,
    parse_final_tool_answer,
)
from .cascade import (
    CASCADE_K,
    CASCADE_N,
    STAGE1_WEIGHT,
    LEAF_WEIGHT,
    LEVEL_WEIGHT,
    CascadeConfig,
    CascadeSource,
    RolloutResponse,
    RolloutResult,
    RolloutAdapter,
    ResponseSegment,
    Stage1Outcome,
    Stage2Outcome,
    CascadeTrajectory,
    CascadeRun,
    CascadeRunner,
    CascadeRolloutRunner,
    build_cascade_stage1_prompt,
    build_cascade_stage2_prompt,
    decode_stage1_candidates,
    decode_stage2_output,
    cascade_reward,
    leave_one_out_advantages,
    compute_rloo_advantages,
    rloo_advantages,
    trajectory_to_policy_records,
    normalize_rollout,
)

__all__ = [
    "NATIVE_TOOL_TRAJECTORY_FORMAT",
    "RlMessage",
    "RewardMeta",
    "RlSample",
    "build_native_tool_prompt",
    "visible_metadata",
    "build_rl_samples",
    "build_rl_row",
    "CategoryToolEnvironment",
    "FinalToolAnswer",
    "exact_tool_reward",
    "parse_final_tool_answer",
    "RewardConfig",
    "RewardResult",
    "FULL_REWARD",
    "INVALID_REWARD",
    "STAGE1_VALID_MISS_DEFAULT",
    "STAGE2_PARTIAL_DEFAULT",
    "reward_stage1",
    "reward_stage2",
    "reward_for_parse_result",
    "reward_stage1_choices",
    "reward_stage2_choices",
    "reward_for_choice_result",
    "RL_SPLITS",
    "VERL_RL_COLUMNS",
    "export_rl_dataset",
    "validate_rl_row",
    "validate_rl_dataset",
    "CASCADE_K",
    "CASCADE_N",
    "STAGE1_WEIGHT",
    "LEAF_WEIGHT",
    "LEVEL_WEIGHT",
    "CascadeConfig",
    "CascadeSource",
    "RolloutResponse",
    "RolloutResult",
    "RolloutAdapter",
    "ResponseSegment",
    "Stage1Outcome",
    "Stage2Outcome",
    "CascadeTrajectory",
    "CascadeRun",
    "CascadeRunner",
    "CascadeRolloutRunner",
    "build_cascade_stage1_prompt",
    "build_cascade_stage2_prompt",
    "decode_stage1_candidates",
    "decode_stage2_output",
    "cascade_reward",
    "leave_one_out_advantages",
    "compute_rloo_advantages",
    "rloo_advantages",
    "trajectory_to_policy_records",
    "normalize_rollout",
]
